# Generated by Django 5.2.14 on 2026-05-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datasource',
            name='suspicious_rows',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datasource',
            name='total_rows',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datasource',
            name='valid_rows',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='reviewed_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='emissionrecord',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('LOCKED', 'LOCKED')], default='PENDING', max_length=20),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['status'], name='ingestion_e_status_a59a4a_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['scope'], name='ingestion_e_scope_94ddb3_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['suspicious'], name='ingestion_e_suspici_4f6a42_idx'),
        ),
    ]
