# Generated by Django 5.2.14 on 2026-05-26 10:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0002_datasource_file_name_datasource_suspicious_rows_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='emissionrecord',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='auditlog',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datasource',
            name='failed_rows',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datasource',
            name='processing_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datasource',
            name='uploaded_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='calculated_emissions',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='emission_factor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='emission_factor_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='external_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='failure_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'CREATE'), ('UPDATE', 'UPDATE'), ('APPROVE', 'APPROVE'), ('REJECT', 'REJECT'), ('LOCK', 'LOCK'), ('FAIL', 'FAIL')], max_length=100),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='ingestion.emissionrecord'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='ingestion.company'),
        ),
        migrations.AlterField(
            model_name='emissionrecord',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='ingestion.company'),
        ),
        migrations.AlterField(
            model_name='emissionrecord',
            name='scope',
            field=models.CharField(choices=[('SCOPE_1', 'Scope 1'), ('SCOPE_2', 'Scope 2'), ('SCOPE_3', 'Scope 3')], max_length=20),
        ),
        migrations.AlterField(
            model_name='emissionrecord',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='ingestion.datasource'),
        ),
        migrations.AlterField(
            model_name='emissionrecord',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('FAILED', 'FAILED'), ('LOCKED', 'LOCKED')], default='PENDING', max_length=20),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['company'], name='ingestion_e_company_dca52e_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['source'], name='ingestion_e_source__f54fe5_idx'),
        ),
    ]
